### ISSUE TITLE
MatLib, Numpy, Pandas is installed, but MGraph is outputting not installed

### ISSUE THREAD

**Issue by mcculzac** [ahnt/MABE#27]
![image](https://cloud.githubusercontent.com/assets/22920376/20323723/f15f6074-ab4b-11e6-88b2-77617aa28bea.png)

Note, running with python as prefixed before runs correctly.  At a guess, using by default a different python install...?

**Comment by cliff-bohm** [comment]
Just to follow up. I have had the same issue, and yes, it ends up I had two pythons installed.

checking version can be tricky if you get into this state because the command line response is different then the script response. I think what I ended up using was:

import sys
print (sys.version)

put these two lines in the command line version and also in a file that you call with python (i.e. python file.py)

if they give different results, you have found your problem!
